### ISSUE TITLE
Minecraft Servers OpBlocks and Penguin(pgg) not logging on

### ISSUE THREAD

**Issue by Spratz8** [GeyserMC/GeyserConnect#80] opened 2023-10-25 21:04 UTC
Minecraft Servers opblocks and penguin pgg say geyser is not working.  Screen shot is the same error message I get on both servers when trying to connect my Bedrock client to either server.  Discord staff of both servers say its a Geyser problem.  I use my laptop for connection for Minecraft and using the Minecraft launcher or 3rd party launcher results in the same message.

![Minecraft 10_25_2023 9_47_43 AM](https://github.com/GeyserMC/GeyserConnect/assets/149017182/ff1b5464-71be-4443-af6d-0cd10d4d862a)

**Comment by Spratz8** [comment] 2023-10-25 21:04
My bedrock account is using my laptop connection.

**Comment by hasankayra04** [comment] 2023-10-25 21:27
Duplicate of [#4240](https://github.com/GeyserMC/Geyser/issues/4240)

**Closed** 2023-10-25 22:57 UTC
Labels: duplicate
